[project]
name = "sodarqc"
version = "0.1.1"
description = "Quality check each range gate of the sodar VT-1"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "polars==1.21.0",
    "simple-term-menu>=1.6.6",
]
