[project]
name = "solarcalc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fpdf2>=2.8.2",
    "numpy>=2.2.3",
    "polars>=1.22.0",
    "streamlit>=1.42.1",
]
